_wandb:
    value:
        cli_version: 0.22.2
        e:
            ceyfgc1sgx680qc9432n45qgt6g9n639:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 128
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: pucci@kth.se
                executable: /opt/conda/envs/py_3.10/bin/python3
                git:
                    commit: 0cf5a0a14956e44463c8a9daf8069fe759603791
                    remote: https://github.com/giuliapucci98/DeepBSVIE.git
                host: nid002822
                memory:
                    total: "539700326400"
                os: Linux-5.14.21-150500.55.65_13.0.73-cray_shasta_c-x86_64-with-glibc2.35
                program: /cfs/klemming/home/p/pucci/PycharmProjects/DeepBSVIE/main.py
                python: CPython 3.10.13
                root: /cfs/klemming/projects/supr/naiss2024-22-1707/DeepBSVIE/reflected_2025-11-15_17-41-09/models
                slurm:
                    cluster_name: dardel
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "128"
                    gpus: "1"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: naiss2024-22-1707-gpu
                    job_cpus_per_node: "128"
                    job_end_time: "1763225704"
                    job_gid: "3224560"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "14092476"
                    job_name: myjob
                    job_nodelist: nid002822
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1763224804"
                    job_uid: "3224560"
                    job_user: pucci
                    jobid: "14092476"
                    localid: "0"
                    mpi_type: cray_shasta
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid002822
                    oom_kill_step: "0"
                    prio_process: "19"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /cfs/klemming/home/p/pucci/PycharmProjects/DeepBSVIE
                    submit_host: login1
                    task_pid: "3220025"
                    tasks_per_node: "128"
                    topology_addr: nid002822
                    topology_addr_pattern: node
                startedAt: "2025-11-15T16:41:21.636619Z"
                writerId: ceyfgc1sgx680qc9432n45qgt6g9n639
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.13
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": linux-x86_64
"N":
    value: 50
T:
    value: 1
batch_size:
    value: 4096
dim_h_Y:
    value: 40
dim_h_Z:
    value: 80
dim_x:
    value: 5
early_stop_threshold:
    value: 1e-05
example_type:
    value: reflected
factor_lr_decay:
    value: 0.5
grad_clip:
    value: false
itr:
    value: 500
lr:
    value: 0.01
lr_decay:
    value: 0.995
max_grad_norm:
    value: 1
mu_base:
    value: 0.1
multiplier:
    value: 3
patience_lr_decay:
    value: 50
seed:
    value: 42
sig_base:
    value: 0.2
use_scheduler:
    value: true
weight_decay:
    value: 1e-05
x0_scale:
    value: 1
